--- 
vlans: 
 - { vlan_id: 100, vlan_name: VLAN100_CFG, vlan: YES}
 - { vlan_id: 1, vlan_name: VLAN1_CFG, vlan: NO}
 - { vlan_id: 200, vlan_name: VLAN200_CFG, vlan: YES}
 - { vlan_id: 2, vlan_name: VLAN2_CFG, vlan: YES}
 - { vlan_id: 500, vlan_name: VLAN500_CFG, vlan: YES}
